// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE4Jr691Z7a7df6AFCL-8dJFuwaoiZ-BE',
    appId: '1:776594823980:web:4f7f2c86e426d7def56a89',
    messagingSenderId: '776594823980',
    projectId: 'local-final',
    authDomain: 'local-final.firebaseapp.com',
    storageBucket: 'local-final.appspot.com',
    measurementId: 'G-TX9X2YERKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2L61sgiP6ZtSIVsvn35dfUZ5s3ofpio',
    appId: '1:776594823980:android:3b008c2eec845e8ff56a89',
    messagingSenderId: '776594823980',
    projectId: 'local-final',
    storageBucket: 'local-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJ4dX5p8V7m1lr7uvznZhqHqJN_h7pdk',
    appId: '1:776594823980:ios:cc63fc9f4bf0bd8cf56a89',
    messagingSenderId: '776594823980',
    projectId: 'local-final',
    storageBucket: 'local-final.appspot.com',
    iosBundleId: 'com.example.localKonekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJ4dX5p8V7m1lr7uvznZhqHqJN_h7pdk',
    appId: '1:776594823980:ios:4ca0d5892d92adb4f56a89',
    messagingSenderId: '776594823980',
    projectId: 'local-final',
    storageBucket: 'local-final.appspot.com',
    iosBundleId: 'com.example.localKonekt.RunnerTests',
  );
}
